### ISSUE TITLE
UNIX socket connect connection refused on rchain.cloud

### ISSUE THREAD

**Issue by whereyouatwimm** [rchain-community/rchain.cloud#31]
Hi there,

Looks like there's an issue with the docker container that processes the smart contracts for rchain.cloud. I get the error message below when trying to run the default Hello World script.

connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown

Please let me know if I can provide any more detail / be of any assistance.

wimm.

**Comment by tschoffelen** [comment]
Hi! Thanks, this is a known bug that we're actually fixing as we speak. It turns out that the RNode software isn't too stable currently, and often crashes. 

We're working on improving our software to detect that and automatically restart the node.

**Comment by tschoffelen** [comment]
Posting all of this here as a reference:

Node bug: https://rchain.atlassian.net/browse/CORE-1003

Full output of the node when it crashes:

```
o.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:517)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:335)
	at scalapb.grpc.Grpc$.completeObserver(Grpc.scala:21)
	at coop.rchain.node.model.repl.ReplGrpc$$anon$2.$anonfun$invoke$2(ReplGrpc.scala:81)
	at coop.rchain.node.model.repl.ReplGrpc$$anon$2.$anonfun$invoke$2$adapted(ReplGrpc.scala:81)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tschoffelen** [comment]
This issue has been resolved, and the app has been pretty stable for the past few days. If you still experience issues, would you mind opening a new issue?
