### ISSUE TITLE
Can't get local instance running

### ISSUE THREAD

**Issue by JoshOrndorff** [rchain-community/rchain.cloud#42]
Following the instructions in the readme:
1. I have Docker `version 18.09.1, build 4c52b90` and Node `v10.15.0`
2. Cloning went fine
3. Dependencies installed fine with `npm install`
4. Started the interface and everything seems normal.

At this point the interface loads and looks perfect. But when I try to run some rholang code, I see rnode errors in the output pane.
```
No certificate found at path /var/lib/rnode/node.certificate.pem
Generating a X.509 certificate for the node
Generating a PEM secret key for the node
Exception in thread "main"
java.io.FileNotFoundException: /var/lib/rnode/node.certificate.pem (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.(FileOutputStream.java:213)
	at java.io.FileOutputStream.(FileOutputStream.java:162)
	at java.io.PrintWriter.(PrintWriter.java:263)
	at coop.rchain.node.NodeRuntime.(node.scala:65)
	at coop.rchain.node.Main$.main(Main.scala:63)
	at coop.rchain.node.Main.main(Main.scala)
```

The console log shows
```
joshy@MicrosoftSurface:~/ProgrammingProjects/rchain.cloud$ PORT=8080 npm start

> rnode.cloud@1.0.0 start /home/joshy/ProgrammingProjects/rchain.cloud
> node index.js

server started on port 8080
pulled rchain/rnode:latest: ok
starting existing container...
started container
a user connected
queue.length: 0
running queue { version: 'latest', body: 'Nil\n' }
Running rchain/rnode:latest with: /tmp/rnode/4ee7f79f-9d64-47f0-a1d3-f1a46c5014e4/input.rho
starting existing container...
attaching
started container
```

I think I'm missing some instructions about  which version of the container to install or something. Do I need to run a  docker command manually? The log messages sound like it started something and definitely those are rnode messages in the output pane. It sounds like there is a permission error on that directory, but that's probably _in_ the container.

Debugging help much appreciated.

More broadly, I'm hoping to get this online at try.rholang.org (hopefully rebranded as "rholang" not "rchain" but first things first).

**Comment by JoshOrndorff** [comment]
`sudo npm start` doesn't help

**Comment by JoshOrndorff** [comment]
`/health` tells me "container is not running". Probably because of non-zero exit code

https://github.com/rchain-community/rchain.cloud/blob/master/index.js#L81-L86

**Comment by JoshOrndorff** [comment]
replacing all 6 occurrences of `latest` with `release-rnode-v0.7` didn't help either.

console log shows:
```
joshy@MicrosoftSurface:~/ProgrammingProjects/rchain.cloud$ PORT=8080 npm start

> rnode.cloud@1.0.0 start /home/joshy/ProgrammingProjects/rchain.cloud
> node index.js

server started on port 8080
pulled rchain/rnode:release-rnode-v0.7: ok
creating container...
create null e10686579dd2ce1eb76ecdc1e09cce2753c7ca8d8e59c43c982485df936f3440
starting container...
writefile null undefined
a user connected
start { Error: (HTTP code 500) server error - OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"sethostname: invalid argument\"": unknown 
    at /home/joshy/ProgrammingProjects/rchain.cloud/node_modules/docker-modem/lib/modem.js:254:17
    at getCause (/home/joshy/ProgrammingProjects/rchain.cloud/node_modules/docker-modem/lib/modem.js:284:7)
    at Modem.buildPayload (/home/joshy/ProgrammingProjects/rchain.cloud/node_modules/docker-modem/lib/modem.js:253:5)
    at IncomingMessage.<anonymous> (/home/joshy/ProgrammingProjects/rchain.cloud/node_modules/docker-modem/lib/modem.js:229:14)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: 'server error',
  statusCode: 500,
  json:
   { message:
      'OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \\"sethostname: invalid argument\\"": unknown' } } null
```

**Comment by JoshOrndorff** [comment]
Looks like that `writefile null undefined` always comes up. Maybe that's where it all goes wrong.

I guess that's this line https://github.com/rchain-community/rchain.cloud/blob/5f76655bc89602f8df772053244d9b1c38080581/lib/DockerManager.js#L110

**Comment by JoshOrndorff** [comment]
Woah! It's suddenly working :confused: I guess I mutated enough local state to make the gods happy.

But srsly, my best guess so far is that pulling the v0.7 release helped.

Re-cloned this repo and reinstalled still working. I'll dig deeper.

**Comment by JoshOrndorff** [comment]
Since it was working locally, I decided to try it on my fresh Ubuntu 18.04 server, fresh docker install, fresh nodejs/npm install.

Similar results like the first time. On my first run:
```
root@rholang:/var/www/try# PORT=8080 npm start

> rnode.cloud@1.0.0 start /var/www/try
> node index.js

server started on port 8080
pulled rchain/rnode:latest: ok
creating container...
create null d87971c7d44a14ab01bd1eeb9d13fedee4d886f92d1054ca61507f41f27fccc7
starting container...
writefile null undefined
start null 
```

**Comment by JoshOrndorff** [comment]
Just simply trying again (not fiddling/fixing/mutating anything) looks better. Maybe the problem is pulling a new docker image?

```
^C
root@rholang:/var/www/try# PORT=8080 npm start

> rnode.cloud@1.0.0 start /var/www/try
> node index.js

server started on port 8080
pulled rchain/rnode:latest: ok
starting existing container...
```

Oh shoot, I can't access 8080 on that server yet...

**Comment by JoshOrndorff** [comment]
All seems to be working now. It did take until the second run of the app to work every time. I guess that's the extent of the bug.
